name: "🚀 publish"

on:
  push:
    branches:
      - release-test
    paths:
      - 'lerna-template-test-package/**'

jobs:
    publish:
      uses: ContextLogic/lerna-symlink-demo/monorepo/.github/workflows/publish.yml@release-test
